"""initial schema

Revision ID: 48a9490a1fa5
Revises: 
Create Date: 2026-03-20 16:34:17.227357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a9490a1fa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave_docente', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_docentes'))
    )
    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docentes_clave_docente'), ['clave_docente'], unique=True)

    op.create_table('planes_estudio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planes_estudio'))
    )
    with op.batch_alter_table('planes_estudio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planes_estudio_clave'), ['clave'], unique=True)

    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_grupo', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('plan_estudio_id', sa.Integer(), nullable=False),
    sa.Column('capacidad_alumnos', sa.Integer(), nullable=False),
    sa.Column('tipo_grupo', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tipo_grupo IN ('normal', 'semi')", name=op.f('ck_grupos_tipo_grupo_valido')),
    sa.CheckConstraint('capacidad_alumnos > 0', name=op.f('ck_grupos_capacidad_positiva')),
    sa.CheckConstraint('semestre >= 1 AND semestre <= 8', name=op.f('ck_grupos_semestre_rango')),
    sa.ForeignKeyConstraint(['plan_estudio_id'], ['planes_estudio.id'], name=op.f('fk_grupos_plan_estudio_id_planes_estudio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grupos'))
    )
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupos_numero_grupo'), ['numero_grupo'], unique=True)
        batch_op.create_index(batch_op.f('ix_grupos_plan_estudio_id'), ['plan_estudio_id'], unique=False)

    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('plan_estudio_id', sa.Integer(), nullable=False),
    sa.Column('tipo_materia', sa.String(length=20), nullable=False),
    sa.Column('etapa', sa.String(length=50), nullable=True),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("modalidad IN ('presencial', 'virtual')", name=op.f('ck_materias_modalidad_valida')),
    sa.CheckConstraint("tipo_materia IN ('normal', 'optativa')", name=op.f('ck_materias_tipo_materia_valido')),
    sa.CheckConstraint('semestre >= 1 AND semestre <= 8', name=op.f('ck_materias_semestre_rango')),
    sa.ForeignKeyConstraint(['plan_estudio_id'], ['planes_estudio.id'], name=op.f('fk_materias_plan_estudio_id_planes_estudio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materias'))
    )
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materias_clave'), ['clave'], unique=True)
        batch_op.create_index(batch_op.f('ix_materias_plan_estudio_id'), ['plan_estudio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materias_semestre'), ['semestre'], unique=False)

    op.create_table('bloques_horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=20), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("dia IN ('lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado')", name=op.f('ck_bloques_horario_dia_valido')),
    sa.CheckConstraint("modalidad IN ('presencial', 'virtual')", name=op.f('ck_bloques_horario_modalidad_valida')),
    sa.CheckConstraint('hora_inicio < hora_fin', name=op.f('ck_bloques_horario_rango_horas_valido')),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], name=op.f('fk_bloques_horario_docente_id_docentes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], name=op.f('fk_bloques_horario_grupo_id_grupos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name=op.f('fk_bloques_horario_materia_id_materias'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bloques_horario'))
    )
    with op.batch_alter_table('bloques_horario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bloques_horario_dia'), ['dia'], unique=False)
        batch_op.create_index(batch_op.f('ix_bloques_horario_docente_id'), ['docente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bloques_horario_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bloques_horario_materia_id'), ['materia_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloques_horario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bloques_horario_materia_id'))
        batch_op.drop_index(batch_op.f('ix_bloques_horario_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_bloques_horario_docente_id'))
        batch_op.drop_index(batch_op.f('ix_bloques_horario_dia'))

    op.drop_table('bloques_horario')
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materias_semestre'))
        batch_op.drop_index(batch_op.f('ix_materias_plan_estudio_id'))
        batch_op.drop_index(batch_op.f('ix_materias_clave'))

    op.drop_table('materias')
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupos_plan_estudio_id'))
        batch_op.drop_index(batch_op.f('ix_grupos_numero_grupo'))

    op.drop_table('grupos')
    with op.batch_alter_table('planes_estudio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planes_estudio_clave'))

    op.drop_table('planes_estudio')
    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docentes_clave_docente'))

    op.drop_table('docentes')
    # ### end Alembic commands ###
