"""add_materia_load_fields

Revision ID: 7247a338a726
Revises: 48a9490a1fa5
Create Date: 2026-03-20 22:50:04.776095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7247a338a726'
down_revision = '48a9490a1fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hc', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('ht', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('hl', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('hpc', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('hcl', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('he', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('cr', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_column('cr')
        batch_op.drop_column('he')
        batch_op.drop_column('hcl')
        batch_op.drop_column('hpc')
        batch_op.drop_column('hl')
        batch_op.drop_column('ht')
        batch_op.drop_column('hc')

    # ### end Alembic commands ###
